spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # можно переопределить через ENV переменную SPRING_PROFILES_ACTIVE
