spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:your_database_name}
    username: ${DB_USER:your_username}
    password: ${DB_PASSWORD:your_password}
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
